### ISSUE TITLE
Inconsistent documentation for variables as boolean

### ISSUE THREAD

**Issue by HoboDev** [gura-conf/gura#16]
In the documentation here: https://gura.netlify.app/docs/spec/#variables
is written: "booleans are not allowed as variable value"

but in section "imports" in the listing of "two.ura"
there is this line: $my_var: true
which is a boolean value on a variable.

Other than that it seems like a very thoughtful config file format.

**Comment by Genarito** [comment]
Hi!

Thank you very much for reporting, evidently there was an error in the documentation and it's just been fixed. In the first drafts of the specs we considered the possibility of defining a variable with a boolean value (or `null`), however, later we decided to remove that feature and we forgot to change the examples. :face_exhaling: 

We hope Gura will be useful for your projects!

**Comment by HoboDev** [comment]
BTW: I've found out that the ABNF grammar still allows for boolean as variable value.
I personally can't see anything wrong with a variable having a boolean or null value. But I'm also not the designer and I'm sure there is some reason behind that.

I think it will be useful. It has some cleanliness which I miss on others.

**Comment by Genarito** [comment]
Oops, we didn't notice that either. It will be corrected during the week as I don't have my computer right now. 
Regarding the reason why boolean or null values are not allowed for variables is that they do not add value to the language as they are unique values and cannot be reused.
To give an example, variables make sense when you want to reuse a value that would be expensive to modify throughout a configuration file:

```
$var: "Some large value that I want to ...."

sample_text_1: $var
sample_text_2: $var
```

The main reason for adding the variables to Gura was to shorten the import statements as shown in the [Import section](https://gura.netlify.app/docs/spec#imports) in the documentation.

```
$common_path: "/extremely/long/path/to/some/useful/directory"

import "$common_path/one.ura"
import "$common_path/two.ura"
```

But with *Singleton* values like `null`, variables **would only be an alias** of them, since the following block:

```
$var: null

sample_value_1: $var
sample_value_2: $var
```

Could be simplified, **without any impact on maintainability**, to:

```
sample_value_1: null
sample_value_2: null
```


Perhaps considering all types of values for a variable can be evaluated in the 2.0.0 version of the language (we could open a [Github Discussion](https://github.com/gura-conf/gura/discussions) or discuss it in real-time through [our Discord server](https://discord.com/invite/Qs5AXPQpKd)). I understand that it could be useful during debugging to change the whole configuration by modifying a single boolean variable. But keep in mind that it would be adding complexity to the language, which is why variable values were only limited to basic values from the beginning.

**Comment by HoboDev** [comment]
> Oops, we didn't notice that either.
That's the beauty of open source. Someone will and hopefully reports it.

I understand the thoughts behind omitting null and true for a variable. Also I don't have a scenario in my head where I would desperately need that. And if someone does they can always work around with an int.

**Comment by Genarito** [comment]
Hi @HoboDev, I finally fixed ABNF grammar. We're going to discuss the incorporation of singleton values in variables and, in case of approval, they'd be added in v2.0.0. Feel free to re-open the issue if you consider it's not fixed yet. :smile: 

Thanks again!
